name: Lint

on: pull_request

jobs:
  lint-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Lint release
        uses: docker://replicated/vendor-cli:latest
        with:
          args: release lint --yaml-dir=manifests
        env:
          REPLICATED_API_TOKEN: ${{ secrets.REPLICATED_API_TOKEN }}
          REPLICATED_APP: ${{ secrets.REPLICATED_APP }}
          REPLICATED_API_ORIGIN: ${{ secrets.REPLICATED_API_ORIGIN }}
